language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake test
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database time_bank_test'